name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only run this job for 'main' branch (setup reference for dual envs: TourismWebsite repo)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH (Auth)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh

          # Write the private key to the id_rsa file
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

          # Set the correct permissions for the private key
          chmod 600 ~/.ssh/id_rsa

          # Add the SSH host key to known_hosts
          ssh-keyscan -p 65002 153.92.9.58 >> ~/.ssh/known_hosts

          # Set the correct permissions for the known_hosts file
          chmod 644 ~/.ssh/known_hosts

          # Start the SSH agent
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa || echo "Error adding SSH key"

      - name: Deploy to Production (app.ventapilot.com)
        run: |
          ssh -v -i ~/.ssh/id_rsa -p 65002 u788653447@153.92.9.58 "
            RED='\033[0;31m'
            GREEN='\033[0;32m'
            YELLOW='\033[1;33m'
            NC='\033[0m' # No Color

            # Explicitly use PHP 8.4 for Composer and Artisan commands available on Hostinger
            PHP84=/opt/alt/php84/usr/bin/php
            # Ensure Composer is available in the PATH or specify its location
            COMPOSER=$(which composer)

            echo -e \"\${YELLOW}🔄 Navigating to VentaPilot Hostinger local repository directory...\${NC}\" &&
            cd domains/ventapilot.com/public_html/subdomains/webapp/ventapilot-webapp &&

            echo -e \"\${YELLOW}⬇️ Pulling latest changes from origin/main...\${NC}\" &&
            git pull origin main &&

            # Install Composer dependencies without dev packages, optimizing the autoloader
            echo -e \"\${YELLOW}📦 Installing Composer dependencies...\${NC}\" &&
            $PHP84 $COMPOSER install --no-interaction --prefer-dist --optimize-autoloader --no-dev &&

            # Run database migrations with the --force flag to bypass confirmation prompts
            echo -e \"\${YELLOW}🛠 Running database migrations...\${NC}\" &&
            $PHP84 artisan migrate --force &&

            # Clear and cache configuration, routes, and views for optimal performance
            echo -e \"\${YELLOW}🧠 Caching config files...\${NC}\" &&
            $PHP84 artisan config:cache &&
            echo -e \"\${YELLOW}🧠 Caching routes...\${NC}\" &&
            $PHP84 artisan route:cache &&
            echo -e \"\${YELLOW}🧠 Caching views...\${NC}\" &&
            $PHP84 artisan view:cache

            echo -e \"\${GREEN}✅ Deployment completed successfully!\${NC}\"
          "
